stages:
  - pre
  - build
  - check
  - upload

update_locale_catalogs:
  stage: pre
  image: dock.heptacle.fr/docker/whlbuild
  script:
    - python3 setup.py extract_messages
    - find canard/locale -maxdepth 1 -mindepth 1 -type d -regex '.*[a-z][a-z][a-z]?_?[A-Z]?[A-Z]?' -exec bash -c 'python3 setup.py update_catalog --locale $(basename {})' \;
  artifacts:
    paths:
      - canard-2.0.pot
      - canard/locale/*/LC_MESSAGES/*.po

.dist: &dist_job
  stage: build
  image: dock.heptacle.fr/docker/whlbuild
  script:
    - find canard/locale -maxdepth 1 -mindepth 1 -type d -regex '.*[a-z][a-z][a-z]?_?[A-Z]?[A-Z]?' -exec bash -c 'python3 setup.py compile_catalog --locale $(basename {})' \;
    - python3 setup.py ${CI_JOB_NAME} ${SETUP_APPEND}
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist/*

sdist:
  <<: *dist_job
  variables:
    SETUP_APPEND: --formats=gztar,bztar,zip

bdist_wheel:
  <<: *dist_job

bdist_egg:
  <<: *dist_job

bdist:
  <<: *dist_job
  variables:
    SETUP_APPEND: --formats=gztar,bztar,zip

twine_check:
  stage: check
  image: dock.heptacle.fr/docker/whlbuild
  script:
    - twine check dist/*
  dependencies:
    - sdist
    - bdist_wheel
    - bdist_egg
    - bdist

twine_upload_test:
  stage: upload
  image: dock.heptacle.fr/docker/whlbuild
  script:
    - 'twine upload --repository-url https://test.pypi.org/legacy/ dist/*'
  dependencies:
    - sdist
    - bdist_wheel
    - bdist_egg
    - bdist
  when: manual